[package]
name = "ov-config"
version = "0.1.0"
authors = ["Boyu Ni <bni@symbolicio.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
